// Code generated by "stringer -type SortKey list.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Updated-1]
	_ = x[Created-2]
	_ = x[Number-3]
	_ = x[Stars-4]
	_ = x[Watches-5]
	_ = x[Comments-6]
	_ = x[BestMatch-7]
}

const _SortKey_name = "UpdatedCreatedNumberStarsWatchesCommentsBestMatch"

var _SortKey_index = [...]uint8{0, 7, 14, 20, 25, 32, 40, 49}

func (i SortKey) String() string {
	i -= 1
	if i < 0 || i >= SortKey(len(_SortKey_index)-1) {
		return "SortKey(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SortKey_name[_SortKey_index[i]:_SortKey_index[i+1]]
}
